package:
  name: pytorchnewtest
  version: 1.0

source:
  git_rev: 1.0
  git_url: https://github.com/liorarueff/pytorchnewtest.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pytorchnewtest

about:
  home: https://github.com/liorarueff/pytorchnewtest
  license: BSD
