package:
  name: pytorchnewtest
  version: 1.0

source:
  url: https://pypi.io/packages/source/p/pytorchnewtest/pytorchnewtest-1.0.tar.gz
  sha256: 2b3a0c466fb4a1014ea131c2b8ea7c519f9278eba73d6fcb361b7bdb4fd494e9

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pytorchnewtest

about:
  home: https://github.com/liorarueff/pytorchnewtest
  license: BSD
